# kustomization.yaml

resources:
  - nginx/nginx.yaml
  - ftp/ftp.yaml
  - mysql/mysql.yaml
  - phpmyadmin/phpmyadmin.yaml
  - wordpress/wordpress.yaml

secretGenerator:
- name: mysql-pass
  literals:
  - password=CHANGE_ME
- name: db-pass
  literals:
  - password=CHANGE_ME
- name: pma-pass
  literals:
  - password=CHANGE_ME
- name: wordpress-database-password
  literals:
  - password=CHANGE_ME
- name: wordpress-admin-password
  literals:
  - password=CHANGE_ME
- name: wordpress-editor-password
  literals:
  - password=CHANGE_ME
- name: wordpress-author-password
  literals:
  - password=CHANGE_ME
- name: wordpress-contributor-password
  literals:
  - password=CHANGE_ME
- name: ssh-user-password
  literals:
  - password=CHANGE_ME
- name: ftp-user-pass
  literals:
  - password=CHANGE_ME
