apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=changeme
- name: db-pass
  literals:
  - password=changeme
- name: pma-pass
  literals:
  - password=changeme
- name: wordpress-database-password
  literals:
  - password=changeme
- name: wordpress-admin-password
  literals:
  - password=changeme
- name: wordpress-editor-password
  literals:
  - password=changeme
- name: wordpress-author-password
  literals:
  - password=changeme
- name: wordpress-contributor-password
  literals:
  - password=changeme
- name: ssh-user
  literals:
  - user=ssh
- name: ssh-user-password
  literals:
  - password=changeme
- name: ftps-user
  literals:
  - user=ftps
- name: ftps-user-pass
  literals:
  - password=changeme

resources:
  - deployments/nginx.yaml
  - deployments/ftps.yaml
  - deployments/mysql.yaml
  - deployments/phpmyadmin.yaml
  - deployments/wordpress.yaml
  - deployments/influxdb.yaml
  - deployments/grafana.yaml
  - deployments/telegraf.yaml
