apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 22
    protocol: TCP
    name: ssh
  selector:
      app: nginx
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
      app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my-nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        imagePullPolicy: Never
