apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240
  ports:
  - port: 21
    protocol: TCP
    name: ftps
  - port: 30020
    protocol: TCP
    name: ftps-passive1
  - port: 30021
    protocol: TCP
    name: ftps-passive2
  - port: 30022
    protocol: TCP
    name: ftps-passive3
  - port: 30023
    protocol: TCP
    name: ftps-passive4
  - port: 30024
    protocol: TCP
    name: ftps-passive5
  - port: 30025
    protocol: TCP
    name: ftps-passive6
  - port: 30026
    protocol: TCP
    name: ftps-passive7
  - port: 30027
    protocol: TCP
    name: ftps-passive8
  - port: 30028
    protocol: TCP
    name: ftps-passive9
  - port: 30029
    protocol: TCP
    name: ftps-passive10
  selector:
      app: ftps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
      app: ftps
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my-ftps
        ports:
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        - containerPort: 30022
        - containerPort: 30023
        - containerPort: 30024
        - containerPort: 30025
        - containerPort: 30026
        - containerPort: 30027
        - containerPort: 30028
        - containerPort: 30029
        imagePullPolicy: Never
        env:
        - name: FTPS_EXTERNAL_IP
          value: 192.168.99.240
        - name: FTPS_USER
          valueFrom:
            secretKeyRef:
              name: ftps-user
              key: user
        - name: FTPS_USER_PASS
          valueFrom:
            secretKeyRef:
              name: ftps-user-pass
              key: password
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: "/vsftpd"
        - mountPath: /etc/vsftpd/vsftpd.conf
          name: ftps-config-volume
          subPath: vsftpd.conf
          readOnly: true
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      - name: ftps-config-volume
        configMap:
          name: ftps-config
