apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      name: grafana
  selector:
    app: grafana
    tier: grafana
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: grafana
    spec:
      containers:
      - image: my-grafana
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
