apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.241
  ports:
    - port: 3000
      protocol: TCP
      name: grafana
  selector:
    app: grafana
    tier: grafana
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: grafana
    spec:
      containers:
      - image: my-grafana
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          name: datasources-provisioning-volume
          subPath: datasources.yaml
          readOnly: true
        - mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
          name: dashboards-provisioning-volume
          subPath: dashboards.yaml
          readOnly: true
        - mountPath: /var/lib/grafana/dashboards/dashboards-metadata.json
          name: dashboards-metadata-volume
          subPath: dashboards-metadata.json
          readOnly: true
      volumes:
      - name: datasources-provisioning-volume
        configMap:
          name: datasources-provisioning
      - name: dashboards-provisioning-volume
        configMap:
          name: dashboards-provisioning
      - name: dashboards-metadata-volume
        configMap:
          name: dashboards-metadata
