apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.242
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 22
    protocol: TCP
    name: ssh
  selector:
      app: nginx
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
      app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my-nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: WEB_PAGE
          value: https://www.42madrid.com
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: ssh-user
              key: user
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh-user-password
              key: password
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-ssh-config-volume
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-ssh-config-volume
        configMap:
          name: nginx-ssh-config
          items:
          - key: nginx-ssh.conf
            path: nginx.conf
