apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 22
    protocol: TCP
    name: ssh
  selector:
      app: nginx
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
      app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my-nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: SSH_USER
          value: sshalpine
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh-user-password
              key: password
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-config-volume
          subPath: telegraf.conf
          readOnly: true
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config-volume
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: telegraf-config-volume
        configMap:
          name: telegraf-config
      - name: nginx-config-volume
        configMap:
          name: nginx-ssh-config
          items:
          - key: nginx-ssh.conf
            path: nginx.conf
