apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: telegraf-config
  files:
  - telegraf.conf
- name: nginx-ssh-config
  files:
  - nginx-ssh.conf
- name: ftps-config
  files:
  - vsftpd.conf
- name: influxdb-config
  files:
  - influxdb.conf
generatorOptions:
  disableNameSuffixHash: true
