apiVersion: v1
kind: Service
metadata:
  name: ftp
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.241
  ports:
  - port: 21
    protocol: TCP
    name: ftp
  - port: 30020
    protocol: TCP
    name: ftp-passive1
  - port: 30021
    protocol: TCP
    name: ftp-passive2
  selector:
      app: ftp
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
      app: ftp
  name: ftp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: my-ftp
        ports:
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        imagePullPolicy: Never
