apiVersion: v1
kind: Service
metadata:
  name: ftp
spec:
  type: LoadBalancer
  ports:
  - port: 21
    protocol: TCP
    name: ftp
  - port: 30020
    protocol: TCP
    name: ftp-passive1
  - port: 30021
    protocol: TCP
    name: ftp-passive2
  selector:
      app: ftp
